//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhapHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuNhapHang()
        {
            this.Chitiet_PhieuNhapHang_SanPham = new HashSet<Chitiet_PhieuNhapHang_SanPham>();
        }
    
        public int maphieunhaphang { get; set; }
        public Nullable<int> manhaphanphoi { get; set; }
        public Nullable<int> manv { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<decimal> tongtien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitiet_PhieuNhapHang_SanPham> Chitiet_PhieuNhapHang_SanPham { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhaPhanPhoi NhaPhanPhoi { get; set; }
    }
}
